/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as DetailsLayoutImport } from './routes/_details-layout'
import { Route as IndexImport } from './routes/index'
import { Route as DetailsLayoutAddressHashImport } from './routes/_details-layout/address.$hash'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const DetailsLayoutRoute = DetailsLayoutImport.update({
  id: '/_details-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DetailsLayoutAddressHashRoute = DetailsLayoutAddressHashImport.update({
  id: '/address/$hash',
  path: '/address/$hash',
  getParentRoute: () => DetailsLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_details-layout': {
      id: '/_details-layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DetailsLayoutImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_details-layout/address/$hash': {
      id: '/_details-layout/address/$hash'
      path: '/address/$hash'
      fullPath: '/address/$hash'
      preLoaderRoute: typeof DetailsLayoutAddressHashImport
      parentRoute: typeof DetailsLayoutImport
    }
  }
}

// Create and export the route tree

interface DetailsLayoutRouteChildren {
  DetailsLayoutAddressHashRoute: typeof DetailsLayoutAddressHashRoute
}

const DetailsLayoutRouteChildren: DetailsLayoutRouteChildren = {
  DetailsLayoutAddressHashRoute: DetailsLayoutAddressHashRoute,
}

const DetailsLayoutRouteWithChildren = DetailsLayoutRoute._addFileChildren(
  DetailsLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof DetailsLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/address/$hash': typeof DetailsLayoutAddressHashRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof DetailsLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/address/$hash': typeof DetailsLayoutAddressHashRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_details-layout': typeof DetailsLayoutRouteWithChildren
  '/about': typeof AboutRoute
  '/_details-layout/address/$hash': typeof DetailsLayoutAddressHashRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '' | '/about' | '/address/$hash'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/about' | '/address/$hash'
  id:
    | '__root__'
    | '/'
    | '/_details-layout'
    | '/about'
    | '/_details-layout/address/$hash'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetailsLayoutRoute: typeof DetailsLayoutRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetailsLayoutRoute: DetailsLayoutRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_details-layout",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_details-layout": {
      "filePath": "_details-layout.tsx",
      "children": [
        "/_details-layout/address/$hash"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_details-layout/address/$hash": {
      "filePath": "_details-layout/address.$hash.tsx",
      "parent": "/_details-layout"
    }
  }
}
ROUTE_MANIFEST_END */
